package Interfaces;



import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import metodos.Jacobi;
import metodos.Gauss;
import metodos.GaussSeidel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

/**
 *
 * @author guifr
 */
public class metodosIterativos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(metodosIterativos.class.getName());

    /**
     * Creates new form metodosIterativos
     */
    public metodosIterativos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_metodosIterativos = new javax.swing.ButtonGroup();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaMatrizA = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecisao = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        radio_GaussSeidel = new javax.swing.JRadioButton();
        radio_Jacobi = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelaMatrizResultado = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaMatrizB = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTamanho = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaMatrizX = new javax.swing.JTable();
        btn_Calcular = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtQuantIteracoes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();

        jButton3.setText("jButton1");

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(254, 224, 224));

        tabelaMatrizA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizA.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizA.setShowGrid(true);
        jScrollPane3.setViewportView(tabelaMatrizA);

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel3.setText("Precisão:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPrecisao, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Escolha o metodo iterativo:");

        buttonGroup_metodosIterativos.add(radio_GaussSeidel);
        radio_GaussSeidel.setText("Gauss-Seidel");
        radio_GaussSeidel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_GaussSeidelActionPerformed(evt);
            }
        });

        buttonGroup_metodosIterativos.add(radio_Jacobi);
        radio_Jacobi.setText("Jacobi");
        radio_Jacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_JacobiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(radio_GaussSeidel)
                        .addGap(18, 18, 18)
                        .addComponent(radio_Jacobi)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_GaussSeidel)
                    .addComponent(radio_Jacobi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelaMatrizResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizResultado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizResultado.setShowGrid(true);
        jScrollPane5.setViewportView(tabelaMatrizResultado);

        tabelaMatrizB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizB.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizB.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaMatrizB);

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 153));
        jLabel9.setText("Métodos Iterativos");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 1, true));

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Gerar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel2.setText("Tamanho da matriz NxN: ");

        txtTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Matriz B");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Matriz A");

        tabelaMatrizX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizX.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizX.setShowGrid(true);
        jScrollPane4.setViewportView(tabelaMatrizX);

        btn_Calcular.setBackground(new java.awt.Color(153, 255, 204));
        btn_Calcular.setText("Calcular");
        btn_Calcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel8.setText("Quantidade de Iterações");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtQuantIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQuantIteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Matriz X - valores iniciais");

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator3.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setBackground(new java.awt.Color(255, 153, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 153));
        jLabel10.setText(" Resultado Final Iterações");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel9))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio_GaussSeidelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_GaussSeidelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_GaussSeidelActionPerformed

    private void radio_JacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_JacobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_JacobiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int n = Integer.parseInt(txtTamanho.getText());

            if (n <= 0) {
                JOptionPane.showMessageDialog(this, "O tamanho da matriz deve ser maior que 0!");
                return; 
            }
            GeraMatrizA();
            GeraMatrizX();
            GeraMatrizB();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Insira um número inteiro válido!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        double [][] A = ArmazenaMatrizA(tabelaMatrizA);
        double[] B = ArmazenaMatrizB(tabelaMatrizB);
        double[] X = ArmazenaMatrizB(tabelaMatrizX); //aproximação inicial
        
        /*
        double[][] A = {{1, -3, 2},{-2, 8, -1},{4, -6, 5}};
        double[] B = {11, -15, 29};
        double[] X = {0, 0, 0};
        PreencherMatrizResultado(tabelaMatrizA,A);
        PreencherVetorResultado(tabelaMatrizB,B);
        PreencherVetorResultado(tabelaMatrizX,X);
        */
        /*
        double[][] A = {{4, 1, 1, 1},{2, -8, 1, -1},{1, 2, -5, 1}, {1, 1, 1, -4}};
        double[] B = {7, -6, -1, -1};
        double[] X = {0, 0, 0, 0};
        PreencherMatrizResultado(tabelaMatrizA,A);
        PreencherVetorResultado(tabelaMatrizB,B);
        PreencherVetorResultado(tabelaMatrizX,X);
        */
        
        if(radio_Jacobi.isSelected()){
            //construido
            Jacobi jacobi = new Jacobi(A, B, X, Integer.parseInt(txtQuantIteracoes.getText()), Double.parseDouble(txtPrecisao.getText()));
            
            //verificar se é convencio
            if(!jacobi.makeDominant())
                JOptionPane.showMessageDialog(this, "Sistema não pode ser diagonalmente dominante, não é convergente! \n Mesmo assim tentaremos executar...");
            //solucao
            double[] valor_final;
            valor_final = jacobi.solve();
            
            GeraMatrizResultado();
            PreencherResultado(tabelaMatrizResultado, valor_final);
            
        }else if(radio_GaussSeidel.isSelected()){
            GaussSeidel gauss = new GaussSeidel(A, B, X, Integer.parseInt(txtQuantIteracoes.getText()), Double.parseDouble(txtPrecisao.getText()));
            //construido
            
            if(!gauss.makeDominant())
                JOptionPane.showMessageDialog(this, "Sistema não pode ser diagonalmente dominante, não é convergente! \n Mesmo assim tentaremos executar...");
            
            double[] valor_final;
            valor_final = gauss.solve();
            
            GeraMatrizResultado();
            PreencherResultado(tabelaMatrizResultado, valor_final);
        }else{
            JOptionPane.showMessageDialog(this, "Precisa selecionar um método!!");
        }
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void txtTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanhoActionPerformed
    }//GEN-LAST:event_txtTamanhoActionPerformed
    
        
    public void PreencherVetorResultado(javax.swing.JTable tabela, double[] resultados) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        if (model.getRowCount() < resultados.length) {
            model.setRowCount(resultados.length);
        }

        for (int i = 0; i < resultados.length; i++) {
            //setValueAt(valor, linha, coluna)
            model.setValueAt(resultados[i], i, 1);
        }

        tabela.revalidate();  
        tabela.repaint();   
    }
    
    public void PreencherMatrizResultado(javax.swing.JTable tabela, double[][] resultados) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        if (model.getRowCount() < resultados.length) {
            model.setRowCount(resultados.length);
        }

        for (int i = 0; i < resultados.length; i++) {
            for(int j = 0; j< resultados.length; j++){
                model.setValueAt(resultados[i][j], i, j+1);
            }
        }

        tabela.revalidate();  
        tabela.repaint();   
    }
    
    public void PreencherResultado(javax.swing.JTable tabela, double[] resultados) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        model.setRowCount(0); 

        Object[] linha = new Object[resultados.length];
        for (int i = 0; i < resultados.length; i++) {
            linha[i] = resultados[i];
        }

        model.addRow(linha);

        tabela.revalidate();  
        tabela.repaint();   
    }
    
    public double[][] ArmazenaMatrizA(javax.swing.JTable tabela) {
        int n = tabela.getRowCount();
        
        double[][] matrizA = new double[n][n];

        for (int i = 0; i < n; i++) {
            //j em 1 para pular a coluna de texto
            for (int j = 1; j < tabela.getColumnCount(); j++) {
                try {
                    Object valor = tabela.getValueAt(i, j);
                    
                    if (valor == null || valor.toString().isEmpty()) {
                        matrizA[i][j - 1] = 0.0;
                    } else {                       
                        matrizA[i][j - 1] = Double.parseDouble(valor.toString());
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro na linha " + (i+1) + ": valor inválido.");
                    return null; 
                }
            }
        }
        return matrizA;
    }
    
    //tambem vale para a matrizX
    public double[] ArmazenaMatrizB(javax.swing.JTable tabela) {
        int n = tabela.getRowCount();
        double[] matrizB = new double[n];

        for (int i = 0; i < n; i++) {
            // só tem uma coluna esse treco
            Object valor = tabela.getValueAt(i, 1);
            matrizB[i] = Double.parseDouble(valor.toString());
        }
        return matrizB;
    }
    
    public void GeraMatrizA(){
        int n = Integer.parseInt(txtTamanho.getText());

        DefaultTableModel matrizA = new DefaultTableModel(n, n+1) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizA.setModel(matrizA);

        //define nome Colunas
        for(int i = 0; i < n+1; i++) {
            if(i == 0) {
                tabelaMatrizA.getColumnModel().getColumn(i).setHeaderValue("Matriz");
            } else {
                tabelaMatrizA.getColumnModel().getColumn(i).setHeaderValue("Coluna: " + i);
            }
        }
        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizA.setValueAt("Linha " + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizA);
        tabelaMatrizA.getTableHeader().repaint();
    }

    public void GeraMatrizX(){
        int n = Integer.parseInt(txtTamanho.getText());

        DefaultTableModel matrizX = new DefaultTableModel(n, 2) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizX.setModel(matrizX);

        //define nome Colunas
        tabelaMatrizX.getColumnModel().getColumn(0).setHeaderValue("Matriz");
        tabelaMatrizX.getColumnModel().getColumn(1).setHeaderValue("Coluna: " + 1);

        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizX.setValueAt("x" + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizX);
        tabelaMatrizX.getTableHeader().repaint();
    }

    public void GeraMatrizB(){
        int n = Integer.parseInt(txtTamanho.getText());

        DefaultTableModel matrizB = new DefaultTableModel(n, 2) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return column != 0;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizB.setModel(matrizB);

        //define nome Colunas
        tabelaMatrizB.getColumnModel().getColumn(0).setHeaderValue("Matriz");
        tabelaMatrizB.getColumnModel().getColumn(1).setHeaderValue("Coluna: " + 1);

        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizB.setValueAt("Linha " + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizB);
        tabelaMatrizB.getTableHeader().repaint();
    }
    
    public void GeraMatrizResultado(){
        int n = Integer.parseInt(txtTamanho.getText());

        DefaultTableModel matrizResultado = new DefaultTableModel(1, n + 2) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return Integer.class; 
                return Double.class;
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabelaMatrizResultado.setModel(matrizResultado);

        tabelaMatrizResultado.getColumnModel().getColumn(0).setHeaderValue("Iteração");
        for(int i = 1; i < n+1; i++) {
            tabelaMatrizResultado.getColumnModel().getColumn(i).setHeaderValue("x" + i);         
        }
        tabelaMatrizResultado.getColumnModel().getColumn(n+1).setHeaderValue("Erro");
        
        tabelaMatrizResultado.getColumnModel().getColumn(0).setPreferredWidth(60);
        for (int i = 1; i < matrizResultado.getColumnCount(); i++) {
            tabelaMatrizResultado.getColumnModel().getColumn(i).setPreferredWidth(100);
           }
        //pintar a cedulas não editaveis
         for (int i = 0; i < tabelaMatrizResultado.getColumnCount(); i++) {
            tabelaMatrizResultado.getColumnModel().getColumn(i).setCellRenderer(renderizador);
         }
        tabelaMatrizResultado.getTableHeader().repaint();
    }
    
    //Pintar a coluna 0 da matriz
    DefaultTableCellRenderer renderizador = new DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, 
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        // Deixamos o Java criar o componente padrão primeiro
        java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        
        if (column == 0 ) {
            c.setBackground(new java.awt.Color(230, 230, 230)); // Um cinza claro
            c.setForeground(java.awt.Color.BLACK);            // Cor do texto
            c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD)); // Texto em negrito
        } else {
            
            c.setBackground(java.awt.Color.WHITE);
            c.setForeground(java.awt.Color.BLACK);
        }
 
        if (isSelected) {
            c.setBackground(table.getSelectionBackground());
        }

        return c;
        }
    };

    public void AjusteTabela(javax.swing.JTable table){
        //ajuste de tamanho da cedula
        for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setPreferredWidth(60);
       }
       //pintar a cedulas não editaveis
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderizador);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new metodosIterativos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.ButtonGroup buttonGroup_metodosIterativos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton radio_GaussSeidel;
    private javax.swing.JRadioButton radio_Jacobi;
    private javax.swing.JTable tabelaMatrizA;
    private javax.swing.JTable tabelaMatrizB;
    private javax.swing.JTable tabelaMatrizResultado;
    private javax.swing.JTable tabelaMatrizX;
    private javax.swing.JTextField txtPrecisao;
    private javax.swing.JTextField txtQuantIteracoes;
    private javax.swing.JTextField txtTamanho;
    // End of variables declaration//GEN-END:variables
}


