/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import metodos.Gauss;

/**
 *
 * @author guifr
 */
public class metodoDireto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(metodoDireto.class.getName());

    /**
     * Creates new form metodoDireto
     */
    public metodoDireto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tabelaMatrizAResultado = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabelaMatrizBResultado = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaMatrizB = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtTamanho8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Calcular = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaMatrizA = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaMatrizXResultado = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.pink);
        setResizable(false);

        jPanel11.setBackground(new java.awt.Color(254, 224, 224));

        tabelaMatrizAResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizAResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizAResultado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizAResultado.setShowGrid(true);
        jScrollPane7.setViewportView(tabelaMatrizAResultado);

        tabelaMatrizBResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizBResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizBResultado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizBResultado.setShowGrid(true);
        jScrollPane8.setViewportView(tabelaMatrizBResultado);

        jSeparator3.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(255, 153, 153));

        tabelaMatrizB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizB.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizB.setShowGrid(true);
        jScrollPane2.setViewportView(tabelaMatrizB);

        jSeparator2.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(255, 153, 153));
        jSeparator2.setToolTipText("");
        jSeparator2.setName(""); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel17.setText("Tamanho da matriz NxN: ");

        txtTamanho8.setForeground(new java.awt.Color(255, 153, 153));
        txtTamanho8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 102, 102))); // NOI18N
        txtTamanho8.setCaretColor(new java.awt.Color(255, 153, 153));
        txtTamanho8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanho8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtTamanho8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setBackground(new java.awt.Color(255, 153, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 153));
        jLabel9.setText(" Resultado");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Matriz A");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Matriz X ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Matriz A");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Matriz B");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Matriz B");

        btn_Calcular.setBackground(new java.awt.Color(153, 255, 204));
        btn_Calcular.setText("Calcular");
        btn_Calcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btn_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CalcularActionPerformed(evt);
            }
        });

        tabelaMatrizA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizA.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizA.setShowGrid(true);
        jScrollPane3.setViewportView(tabelaMatrizA);

        tabelaMatrizXResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelaMatrizXResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelaMatrizXResultado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabelaMatrizXResultado.setShowGrid(true);
        jScrollPane6.setViewportView(tabelaMatrizXResultado);

        jButton1.setBackground(new java.awt.Color(153, 255, 204));
        jButton1.setText("Gerar");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 153, 153));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 153, 153));
        jLabel12.setText("Eliminação de Gauss");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153)));

        jSeparator4.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(1091, 1091, 1091))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(366, 366, 366))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel11Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel11Layout.createSequentialGroup()
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(440, 440, 440)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(12, 12, 12)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 981, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int n = Integer.parseInt(txtTamanho8.getText());

            if (n <= 0) {
                JOptionPane.showMessageDialog(this, "O tamanho da matriz deve ser maior que 0!");
                return;
            }
            GeraMatrizA(tabelaMatrizA, true );
            GeraMatrizB(tabelaMatrizB, true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Insira um número inteiro válido!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CalcularActionPerformed
        //double[][] A = ArmazenaMatrizA(tabelaMatrizA);
        //double[] B = ArmazenaMatrizB(tabelaMatrizB);

        //teste no código 
        
        double[][] A = {{1, -3, 2},{-2, 8, -1},{4, -6, 5}};
        double[] B = {11, -15, 29};
        //double[] X = {0, 0, 0};
        PreencherMatrizResultado(tabelaMatrizA,A);
        PreencherVetorResultado(tabelaMatrizB,B);
        
        /*
        double[][] A = {{4, 1, 1, 1},{2, -8, 1, -1},{1, 2, -5, 1}, {1, 1, 1, -4}};
        double[] B = {7, -6, -1, -1};
        double[] X;
        PreencherMatrizResultado(tabelaMatrizA,A);
        PreencherVetorResultado(tabelaMatrizB,B);
        */
        double[][] Aresultado;
        double[] Bresultado;
        double[] Xresultado;

        Gauss gauss = new Gauss();
            
        
        try{
            Gauss.ResultadoGauss resultado = gauss.EliminacaoGauss(A, B);
            Aresultado = resultado.matrizA;
            Bresultado = resultado.matrizB;
            Xresultado = resultado.matrizX;
        }catch(ArithmeticException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            return ;
        }
        
        GeraMatrizA(tabelaMatrizAResultado, false);
        GeraMatrizB(tabelaMatrizBResultado, false);
        GeraMatrizX(tabelaMatrizXResultado, false);
        PreencherMatrizResultado(tabelaMatrizAResultado,Aresultado);
        PreencherVetorResultado(tabelaMatrizBResultado,Bresultado);
        PreencherVetorResultado(tabelaMatrizXResultado,Xresultado);
    }//GEN-LAST:event_btn_CalcularActionPerformed

    private void txtTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanhoActionPerformed

    }//GEN-LAST:event_txtTamanhoActionPerformed
              
    public void PreencherVetorResultado(javax.swing.JTable tabela, double[] resultados) {
    DefaultTableModel model = (DefaultTableModel) tabela.getModel();

    if (model.getRowCount() < resultados.length) {
        model.setRowCount(resultados.length);
    }

    for (int i = 0; i < resultados.length; i++) {
        //setValueAt(valor, linha, coluna)
        model.setValueAt(resultados[i], i, 1);
    }

    tabela.revalidate();  
    tabela.repaint();   
}
    
    public void PreencherMatrizResultado(javax.swing.JTable tabela, double[][] resultados) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();

        if (model.getRowCount() < resultados.length) {
            model.setRowCount(resultados.length);
        }

        for (int i = 0; i < resultados.length; i++) {
            for(int j = 0; j< resultados.length; j++){
                model.setValueAt(resultados[i][j], i, j+1);
            }
        }

        tabela.revalidate();  
        tabela.repaint();   
    }
    
    public double[][] ArmazenaMatrizA(javax.swing.JTable tabela) {
        int n = tabela.getRowCount();
        
        double[][] matrizA = new double[n][n];

        for (int i = 0; i < n; i++) {
            //j em 1 para pular a coluna de texto
            for (int j = 1; j < tabela.getColumnCount(); j++) {
                try {
                    Object valor = tabela.getValueAt(i, j);
                    
                    if (valor == null || valor.toString().isEmpty()) {
                        matrizA[i][j - 1] = 0.0;
                    } else {                       
                        matrizA[i][j - 1] = Double.parseDouble(valor.toString());
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro na linha " + (i+1) + ": valor inválido.");
                    return null; 
                }
            }
        }
        return matrizA;
    }
    
    //tambem vale para a matrizX
    public double[] ArmazenaMatrizB(javax.swing.JTable tabela) {
        int n = tabela.getRowCount();
        double[] matrizB = new double[n];

        for (int i = 0; i < n; i++) {
            // só tem uma coluna esse treco
            Object valor = tabela.getValueAt(i, 1);
            matrizB[i] = Double.parseDouble(valor.toString());
        }
        return matrizB;
    }
  
    //1° passa a tabela em questão para ser gerada, 
    //2° true = editavel, false = não editável
    public void GeraMatrizA(javax.swing.JTable tabelaMatrizA, boolean EDITAVEL){
        int n = Integer.parseInt(txtTamanho8.getText());

        DefaultTableModel matrizA = new DefaultTableModel(n, n+1) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                if(EDITAVEL)
                    return column != 0;
                else
                    return EDITAVEL;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizA.setModel(matrizA);

        //define nome Colunas
        for(int i = 0; i < n+1; i++) {
            if(i == 0) {
                tabelaMatrizA.getColumnModel().getColumn(i).setHeaderValue("Matriz");
            } else {
                tabelaMatrizA.getColumnModel().getColumn(i).setHeaderValue("Coluna: " + i);
            }
        }
        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizA.setValueAt("Linha " + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizA);
        tabelaMatrizA.getTableHeader().repaint();
    }

    public void GeraMatrizX(javax.swing.JTable tabelaMatrizX, boolean EDITAVEL){
        int n = Integer.parseInt(txtTamanho8.getText());

        DefaultTableModel matrizX = new DefaultTableModel(n, 2) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                if(EDITAVEL)
                    return column != 0;
                else
                    return EDITAVEL;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizX.setModel(matrizX);

        //define nome Colunas
        tabelaMatrizX.getColumnModel().getColumn(0).setHeaderValue("Matriz");
        tabelaMatrizX.getColumnModel().getColumn(1).setHeaderValue("Coluna: " + 1);

        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizX.setValueAt("x" + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizX);
        tabelaMatrizX.getTableHeader().repaint();
    }

    public void GeraMatrizB(javax.swing.JTable tabelaMatrizB, boolean EDITAVEL){
        int n = Integer.parseInt(txtTamanho8.getText());

        DefaultTableModel matrizB = new DefaultTableModel(n, 2) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                if (columnIndex == 0) return String.class; // Coluna de rótulos
                return Double.class; // Colunas de valores numéricos
            }
            @Override
            public boolean isCellEditable(int row, int column) {
                if(EDITAVEL)
                    return column != 0;
                else
                    return EDITAVEL;
            }
        };

        // Aplica o novo modelo à sua tabela
        tabelaMatrizB.setModel(matrizB);

        //define nome Colunas
        tabelaMatrizB.getColumnModel().getColumn(0).setHeaderValue("Matriz");
        tabelaMatrizB.getColumnModel().getColumn(1).setHeaderValue("Coluna: " + 1);

        //define nome Linhas
        for(int i = 0; i < n; i++) {
            // Definimos o valor da célula na Linha 'i', Coluna 0
            tabelaMatrizB.setValueAt("Linha " + (i + 1), i, 0);
        }       

        AjusteTabela(tabelaMatrizB);
        tabelaMatrizB.getTableHeader().repaint();
    }
    
    DefaultTableCellRenderer renderizador = new DefaultTableCellRenderer() {
    @Override
    public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, 
            boolean isSelected, boolean hasFocus, int row, int column) {
        
        // Deixamos o Java criar o componente padrão primeiro
        java.awt.Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

        
        if (column == 0 ) {
            c.setBackground(new java.awt.Color(230, 230, 230)); // Um cinza claro
            c.setForeground(java.awt.Color.BLACK);            // Cor do texto
            c.setFont(c.getFont().deriveFont(java.awt.Font.BOLD)); // Texto em negrito
        } else {
            
            c.setBackground(java.awt.Color.WHITE);
            c.setForeground(java.awt.Color.BLACK);
        }
 
        if (isSelected) {
            c.setBackground(table.getSelectionBackground());
        }

        return c;
        }
    };
    
    public void AjusteTabela(javax.swing.JTable table){
        //ajuste de tamanho da cedula
        for (int i = 0; i < table.getColumnCount(); i++) {
                table.getColumnModel().getColumn(i).setPreferredWidth(60);
       }
       //pintar a cedulas não editaveis
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(renderizador);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new metodoDireto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Calcular;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tabelaMatrizA;
    private javax.swing.JTable tabelaMatrizAResultado;
    private javax.swing.JTable tabelaMatrizB;
    private javax.swing.JTable tabelaMatrizBResultado;
    private javax.swing.JTable tabelaMatrizXResultado;
    private javax.swing.JTextField txtTamanho8;
    // End of variables declaration//GEN-END:variables
}
